language: scala

scala:
  - 2.13.5

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

stages:
  - name: lint
  - name: test
  - name: publish
    if: branch = master AND type = push

jobs:
  include:
    - stage: lint
      name: "Check source code formatting"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Build and test for Scala 2.13"
      before_script: gpg --import project/ci.asc
      script: sbt ++$TRAVIS_SCALA_VERSION test package packageSrc publishLocal
    - <<: *test
      scala: 2.12.13
      name: "Build and test for Scala 2.12"
    - <<: *test
      scala: 3.0.0-RC1
      name: "Build and test for Scala 3.0"
    - &publish
      stage: publish
      name: "Publish"
      before_script: gpg --import project/ci.asc
      script: sbt +publish sonatypeBundleReleaseIfNotSnapshot

env:
  global:
